import Mathlib.FieldTheory.PrimitiveElement
import Mathlib.FieldTheory.SeparableClosure
import Mathlib.FieldTheory.Galois.Basic

/-!
Field-theory source wrappers for the recursive Belyi stack.

Mochizuki's proof of the projective-line reduction uses finite extensions,
primitive elements, separability, normal/Galois descent, and conjugating roots
inside a normal extension.  This module exposes the checked Mathlib layer in a
stable namespace for Hilbert benchmarks.
-/

noncomputable section

open scoped IntermediateField Polynomial

namespace HilbertTest
namespace SourceStack
namespace FieldTheory

universe u v w

variable (F E : Type*) [Field F] [Field E] [Algebra F E]

/-- A finite separable field extension has a primitive element. -/
theorem primitive_element_exists
    [FiniteDimensional F E] [Algebra.IsSeparable F E] :
    ∃ α : E, F⟮α⟯ = ⊤ :=
  Field.exists_primitive_element F E

/-- If there are finitely many intermediate fields, every intermediate field is
generated by one element. -/
theorem primitive_element_exists_of_finite_intermediateField
    [Finite (IntermediateField F E)] (K : IntermediateField F E) :
    ∃ α : E, F⟮α⟯ = K :=
  Field.exists_primitive_element_of_finite_intermediateField F E K

/-- An algebraic simple field extension is finite-dimensional. -/
theorem finiteDimensional_of_exists_primitive_element
    [Algebra.IsAlgebraic F E]
    (h : ∃ α : E, F⟮α⟯ = ⊤) :
    FiniteDimensional F E :=
  Field.FiniteDimensional.of_exists_primitive_element F E h

/-- An algebraic simple field extension has finitely many intermediate fields. -/
theorem finite_intermediateField_of_exists_primitive_element
    [Algebra.IsAlgebraic F E]
    (h : ∃ α : E, F⟮α⟯ = ⊤) :
    Finite (IntermediateField F E) :=
  Field.finite_intermediateField_of_exists_primitive_element F E h

/-- Steinitz primitive-element criterion in the finite-intermediate-field form. -/
theorem exists_primitive_element_iff_finite_intermediateField :
    (Algebra.IsAlgebraic F E ∧ ∃ α : E, F⟮α⟯ = ⊤) ↔
      Finite (IntermediateField F E) :=
  Field.exists_primitive_element_iff_finite_intermediateField F E

/-- Adjoining one integral element gives a finite-dimensional field extension. -/
theorem adjoin_finiteDimensional {x : E} (hx : IsIntegral F x) :
    FiniteDimensional F F⟮x⟯ :=
  IntermediateField.adjoin.finiteDimensional hx

/-- Adjoining finitely many integral elements gives a finite-dimensional field
extension. -/
theorem finiteDimensional_adjoin {S : Set E} [Finite S]
    (hS : ∀ x ∈ S, IsIntegral F x) :
    FiniteDimensional F (IntermediateField.adjoin F S) :=
  IntermediateField.finiteDimensional_adjoin hS

/-- The degree of a simple integral extension is the degree of the minimal
polynomial. -/
theorem adjoin_finrank_eq_minpoly_natDegree {x : E} (hx : IsIntegral F x) :
    Module.finrank F F⟮x⟯ = (minpoly F x).natDegree :=
  IntermediateField.adjoin.finrank hx

/-- Separability of a simple adjoin is separability of the adjoined element. -/
theorem isSeparable_adjoin_simple_iff_isSeparable {x : E} :
    Algebra.IsSeparable F F⟮x⟯ ↔ IsSeparable F x :=
  IntermediateField.isSeparable_adjoin_simple_iff_isSeparable F E

/-- Two separable elements generate a separable two-generator extension. -/
theorem isSeparable_adjoin_pair_of_isSeparable {x y : E}
    (hx : IsSeparable F x) (hy : IsSeparable F y) :
    Algebra.IsSeparable F F⟮x, y⟯ :=
  IntermediateField.isSeparable_adjoin_pair_of_isSeparable F E hx hy

/-- Separability of an arbitrary adjoin is pointwise separability of the
generators. -/
theorem isSeparable_adjoin_iff_isSeparable {S : Set E} :
    Algebra.IsSeparable F (IntermediateField.adjoin F S) ↔
      ∀ x ∈ S, IsSeparable F x :=
  IntermediateField.isSeparable_adjoin_iff_isSeparable F E

/-- The degree of the minimal polynomial is bounded by the extension degree. -/
theorem minpoly_natDegree_le
    (x : E) [FiniteDimensional F E] :
    (minpoly F x).natDegree ≤ Module.finrank F E :=
  minpoly.natDegree_le (K := F) x

/-- The degree of an integral element's minimal polynomial divides the finite
extension degree. -/
theorem minpoly_degree_dvd {x : E} (hx : IsIntegral F x) :
    (minpoly F x).natDegree ∣ Module.finrank F E :=
  minpoly.degree_dvd hx

/-- A Galois extension is exactly a separable normal extension. -/
theorem galois_iff :
    IsGalois F E ↔ Algebra.IsSeparable F E ∧ Normal F E :=
  _root_.isGalois_iff

/-- Elements of a Galois extension are integral over the base. -/
theorem isGalois_integral [IsGalois F E] (x : E) :
    IsIntegral F x :=
  IsGalois.integral F x

/-- Elements of a Galois extension are separable over the base. -/
theorem isGalois_separable [IsGalois F E] (x : E) :
    IsSeparable F x :=
  IsGalois.separable F x

/-- Minimal polynomials split in a Galois extension. -/
theorem isGalois_splits [IsGalois F E] (x : E) :
    Polynomial.Splits (algebraMap F E) (minpoly F x) :=
  IsGalois.splits F x

/-- In a finite-dimensional Galois extension, the automorphism-group cardinality
equals the field degree. -/
theorem isGalois_card_aut_eq_finrank
    [FiniteDimensional F E] [IsGalois F E] :
    Fintype.card (E ≃ₐ[F] E) = Module.finrank F E :=
  IsGalois.card_aut_eq_finrank F E

/-- Normality is integrality plus splitting of every minimal polynomial. -/
theorem normal_criterion :
    Normal F E ↔
      ∀ x : E, IsIntegral F x ∧ Polynomial.Splits (algebraMap F E) (minpoly F x) :=
  _root_.normal_iff

/-- Elements of a normal extension are integral over the base. -/
theorem normal_isIntegral [Normal F E] (x : E) :
    IsIntegral F x :=
  Normal.isIntegral (inferInstance : Normal F E) x

/-- Minimal polynomials split in a normal extension. -/
theorem normal_splits [Normal F E] (x : E) :
    Polynomial.Splits (algebraMap F E) (minpoly F x) :=
  Normal.splits (inferInstance : Normal F E) x

/-- A finite-dimensional normal extension is a splitting field. -/
theorem normal_exists_isSplittingField
    [Normal F E] [FiniteDimensional F E] :
    ∃ p : F[X], Polynomial.IsSplittingField F E p :=
  Normal.exists_isSplittingField F E

/-- In a normal extension, roots of a minimal polynomial are connected by a base
field automorphism. -/
theorem minpoly_exists_algEquiv_of_root
    [Normal F E] {x y : E} (hy : IsAlgebraic F y)
    (h_ev : (Polynomial.aeval x) (minpoly F y) = 0) :
    ∃ σ : E ≃ₐ[F] E, σ x = y :=
  minpoly.exists_algEquiv_of_root hy h_ev

/-- The inverse conjugacy direction for roots of a minimal polynomial in a
normal extension. -/
theorem minpoly_exists_algEquiv_of_root'
    [Normal F E] {x y : E} (hy : IsAlgebraic F y)
    (h_ev : (Polynomial.aeval x) (minpoly F y) = 0) :
    ∃ σ : E ≃ₐ[F] E, σ y = x :=
  minpoly.exists_algEquiv_of_root' hy h_ev

variable (K : Type*) [Field K] [Algebra F K] [Algebra K E]
variable [IsScalarTower F K E]

/-- Automorphisms of a normal tower restrict surjectively to the normal
subextension. -/
theorem restrictNormalHom_surjective
    [Normal F K] [Normal F E] :
    Function.Surjective (AlgEquiv.restrictNormalHom K :
      (E ≃ₐ[F] E) → K ≃ₐ[F] K) :=
  AlgEquiv.restrictNormalHom_surjective E

end FieldTheory
end SourceStack
end HilbertTest
